const data = [
    { 
        sisID:"1521",
        langID:"en"  
    },
    { 
        sisID:"1527",
        langID:"de"  
    },
    { 
        sisID:"1526",
        langID:"fr"  
    },    
    { 
        sisID:"1528",
        langID:"es"  
    },    
    { 
        sisID:"1529",
        langID:"it"  
    },    
    { 
        sisID:"1530",
        langID:"sv"  
    },    
    { 
        sisID:"1534",
        langID:"s5"  
    },
    { 
        sisID:"1535",
        langID:"s4"  
    },
    { 
        sisID:"1536",
        langID:"s6"  
    },
    { 
        sisID:"1531",
        langID:"no"  
    },
    { 
        sisID:"1532",
        langID:"da"  
    },
    { 
        sisID:"1537",
        langID:"at"  
    },
    { 
        sisID:"1533",
        langID:"fi"  
    },
    { 
        sisID:"1540",
        langID:"nl"  
    },
    { 
        sisID:"1539",
        langID:"be"  
    },
    { 
        sisID:"1538",
        langID:"b4"  
    },
    { 
        sisID:"1532",
        langID:"da"  
    },
    { 
        sisID:"1532",
        langID:"da"  
    },

];